In [1]:
# 시리즈 연산

import pandas as pd

dict_data = {
    "국어" : 100, 
    "영어" : 80,
    "수학" : 90,

    }

student1 = pd.Series(dict_data)
student1

국어    100
영어     80
수학     90
dtype: int64

In [3]:
percentage = student1 /200

In [4]:
percentage

국어    0.50
영어    0.40
수학    0.45
dtype: float64

In [6]:
print(type(percentage))

<class 'pandas.Series'>

In [8]:
p2 = student1 * 0.5
p2

국어    50.0
영어    40.0
수학    45.0
dtype: float64

In [11]:
## 시리즈 vs 시리즈

dict_data1= {
    "국어" : 100, 
    "영어" : 80,
    "수학" : 90,

    }
dict_data2= {
    "수학" : 80,
    "국어" : 90, 
    "영어" : 80,

    }


student1 = pd.Series(dict_data1)
student2 = pd.Series(dict_data2)

print(student1)
print()
print(student2)

국어    100
영어     80
수학     90
dtype: int64

수학    80
국어    90
영어    80
dtype: int64

In [12]:
addition = student1 + student2

print(type(addition))
addition

<class 'pandas.Series'>

국어    190
수학    170
영어    160
dtype: int64

In [15]:
substraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2

print(addition)
print(substraction)
print(multiplication)
print(division)

국어    190
수학    170
영어    160
dtype: int64
국어    10
수학    10
영어     0
dtype: int64
국어    9000
수학    7200
영어    6400
dtype: int64
국어    1.111111
수학    1.125000
영어    1.000000
dtype: float64

In [19]:
lis = [
    addition,
    substraction,
    multiplication,
    division

]
result = pd.DataFrame(lis, index= ["덧셈","뺄셈","곱셈", "나눗셈"])

result

              국어        수학      영어
덧셈    190.000000   170.000   160.0
뺄셈     10.000000    10.000     0.0
곱셈   9000.000000  7200.000  6400.0
나눗셈     1.111111     1.125     1.0

In [22]:
## NaN 값이 있는 시리즈 연산

import pandas as pd
import numpy as np

dict_data1= {
    "국어" : np.nan, 
    "영어" : 80,
    "수학" : 90,

    }
dict_data2= {
    "수학" : 80,
    "국어" : 90, 
    

    }

In [23]:
student1 = pd.Series(dict_data1)
student2 = pd.Series(dict_data2)

print(student1)
print()
print(student2)

국어     NaN
영어    80.0
수학    90.0
dtype: float64

수학    80
국어    90
dtype: int64

In [24]:
addition = student1 + student2
addition

국어      NaN
수학    170.0
영어      NaN
dtype: float64

In [27]:
substraction = student1 - student2
multiplication = student1 * student2
division = student1 / student2

result = pd.DataFrame([addition,substraction,multiplication,division],index=["덧셈","뺄셈","곱셈","나눗셈"])
result

     국어        수학  영어
덧셈  NaN   170.000 NaN
뺄셈  NaN    10.000 NaN
곱셈  NaN  7200.000 NaN
나눗셈 NaN     1.125 NaN

In [29]:
## 연산메소드

import pandas as pd
import numpy as np

dict_data1= {
    "국어" : np.nan, 
    "영어" : 80,
    "수학" : 90,

    }
dict_data2= {
    "수학" : 80,
    "국어" : 90, 
    

    }

student1 = pd.Series(dict_data1)
student2 = pd.Series(dict_data2)

sr_add = student1.add(student2,fill_value=0)
sr_sub = student1.sub(student2,fill_value=0)
sr_mul = student1.mul(student2,fill_value=0)
sr_div = student1.div(student2,fill_value=0)


lis = [sr_add,sr_sub,sr_mul,sr_div]


result = pd.DataFrame(lis, index=["덧셈","뺄셈","곱셈","나눗셈"])
result

       국어        수학    영어
덧셈   90.0   170.000  80.0
뺄셈  -90.0    10.000  80.0
곱셈    0.0  7200.000   0.0
나눗셈   0.0     1.125   inf

In [30]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (2.4.6)
Requirement already satisfied: pandas>=1.2 in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.0.3)
Collecting matplotlib!=3.6.1,>=3.4 (from seaborn)
  Downloading matplotlib-3.10.9-cp314-cp314-win_amd64.whl.metadata (52 kB)
Collecting contourpy>=1.0.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\Win11Pro\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Collecting pillow>=8 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
Collecting pyparsing>=3 (from matplotlib!=3.6.1,>=3.4->seaborn)
  Downloading pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\Win11Pro\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\Win11Pro\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Downloading matplotlib-3.10.9-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   -------------------------------------- - 8.1/8.3 MB 42.5 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 36.4 MB/s  0:00:00
Downloading contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Downloading cycler-0.12.1-py3-none-any.whl (8.3 kB)
Downloading fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 25.0 MB/s  0:00:00
Downloading kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Downloading pillow-12.2.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 7.2/7.2 MB 39.2 MB/s  0:00:00
Downloading pyparsing-3.3.2-py3-none-any.whl (122 kB)
Installing collected packages: pyparsing, pillow, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn

   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   ----- ---------------------------------- 1/8 [pillow]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   --------------- ------------------------ 3/8 [fonttools]
   -------------------- ------------------- 4/8 [cycler]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ------------------------------ --------- 6/8 [matplotlib]
   ----------------------------------- ---- 7/8 [seaborn]
   ---------------------------------------- 8/8 [seaborn]

Successfully installed contourpy-1.3.3 cycler-0.12.1 fonttools-4.63.0 kiwisolver-1.5.0 matplotlib-3.10.9 pillow-12.2.0 pyparsing-3.3.2 seaborn-0.13.2

In [45]:
# 데이터 프레임 연산

## 데이터프레임 숫자


import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
print(titanic.head())


titanic.shape

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

(891, 15)

In [46]:
df = titanic.loc[ : ,["age","fare"]]
df.head(10)

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500
5   NaN   8.4583
6  54.0  51.8625
7   2.0  21.0750
8  27.0  11.1333
9  14.0  30.0708

In [47]:
addition = df + 10
addition.head(10)

    age     fare
0  32.0  17.2500
1  48.0  81.2833
2  36.0  17.9250
3  45.0  63.1000
4  45.0  18.0500
5   NaN  18.4583
6  64.0  61.8625
7  12.0  31.0750
8  37.0  21.1333
9  24.0  40.0708

In [50]:
## 데이터 프레임 VS 데이터 프레임

import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")
df = titanic.loc[:,["age","fare"]]
df.tail()

      age   fare
886  27.0  13.00
887  19.0  30.00
888   NaN  23.45
889  26.0  30.00
890  32.0   7.75

In [51]:
addition = df + 10

addition.tail()

      age   fare
886  37.0  23.00
887  29.0  40.00
888   NaN  33.45
889  36.0  40.00
890  42.0  17.75

In [ ]:
substraction = addition - df

substraction.tail()

      age  fare
886  10.0  10.0
887  10.0  10.0
888   NaN  10.0
889  10.0  10.0
890  10.0  10.0

In [57]:
sample1 = addition.tail(10)
sample1.shape
sample1

      age     fare
881  43.0  17.8958
882  32.0  20.5167
883  38.0  20.5000
884  35.0  17.0500
885  49.0  39.1250
886  37.0  23.0000
887  29.0  40.0000
888   NaN  33.4500
889  36.0  40.0000
890  42.0  17.7500

In [60]:
sample2 = substraction.tail(10).fillna(0)
sample2

      age  fare
881  10.0  10.0
882  10.0  10.0
883  10.0  10.0
884  10.0  10.0
885  10.0  10.0
886  10.0  10.0
887  10.0  10.0
888   0.0  10.0
889  10.0  10.0
890  10.0  10.0

In [ ]:
df_add = sample1.add(sample2,fill_value=0)
df_sub = sample1.sub(sample2,fill_value=0)
df_mul = sample1.mul(sample2,fill_value=0)
df_div = sample1.div(sample2,fill_value=0)


print(df_add.)
print(df_sub)
print(df_mul)
print(df_div)

      age     fare
881  53.0  27.8958
882  42.0  30.5167
883  48.0  30.5000
884  45.0  27.0500
885  59.0  49.1250
886  47.0  33.0000
887  39.0  50.0000
888   0.0  43.4500
889  46.0  50.0000
890  52.0  27.7500
      age     fare
881  33.0   7.8958
882  22.0  10.5167
883  28.0  10.5000
884  25.0   7.0500
885  39.0  29.1250
886  27.0  13.0000
887  19.0  30.0000
888   0.0  23.4500
889  26.0  30.0000
890  32.0   7.7500
       age     fare
881  430.0  178.958
882  320.0  205.167
883  380.0  205.000
884  350.0  170.500
885  490.0  391.250
886  370.0  230.000
887  290.0  400.000
888    0.0  334.500
889  360.0  400.000
890  420.0  177.500
     age     fare
881  4.3  1.78958
882  3.2  2.05167
883  3.8  2.05000
884  3.5  1.70500
885  4.9  3.91250
886  3.7  2.30000
887  2.9  4.00000
888  NaN  3.34500
889  3.6  4.00000
890  4.2  1.77500

In [62]:
dfg = sns.load_dataset("diamonds")
dfg

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]