In [14]:
import pandas as pd

exam_data = {
    "이름" : ["서준", "우현", "인아"],    
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [95, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   95  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [15]:
print(df.ndim)
print(df.shape)

2
(3, 5)

In [16]:
ndf = df.set_index("이름")

In [17]:
ndf

    수학  영어   음악   체육
이름
서준  90  98   95  100
우현  80  89   95   90
인아  70  95  100   90

In [18]:
ndf2 = ndf.set_index("음악")
ndf2

     수학  영어   체육
음악
95   90  98  100
95   80  89   90
100  70  95   90

In [19]:
ndf3 = ndf.set_index(["수학","음악"])
ndf3

        영어   체육
수학 음악
90 95   98  100
80 95   89   90
70 100  95   90

In [22]:
# 행인덱스의 재배열

import pandas as pd

dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 12],
    "c4" : [13, 14, 15]
}

df = pd.DataFrame(dict_data,index = ["r0","r1","r2"])

In [23]:
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [24]:
new_index = ["r0","r1","r2","r3","r4"]
ndf = df.reindex(new_index)
ndf

     c0   c1   c2    c3    c4
r0  1.0  4.0  7.0  10.0  13.0
r1  2.0  5.0  8.0  11.0  14.0
r2  3.0  6.0  9.0  12.0  15.0
r3  NaN  NaN  NaN   NaN   NaN
r4  NaN  NaN  NaN   NaN   NaN

In [25]:
ndf2 = df.reindex(new_index,fill_value=0)
ndf2

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15
r3   0   0   0   0   0
r4   0   0   0   0   0

In [31]:
# [문제 1] Series 생성 및 변수명 지정 

# 다음 데이터를 활용하여 Pandas Series를 생성하세요. 
# 생성할 때 데이터의 의미가 잘 드러나도록 명확한 변수명을 지정해야 합니다.

# [85, 92, 78, 90, 88] 리스트를 사용하여 5명의 학생 점수를 담은 Series를 만드세요.

# 위에서 만든 Series에 ['Alice', 'Bob', 'Charlie', 'David', 'Eve']라는 문자열 리스트를 인덱스(Index)로 지정하세요.

# 과목별 과제 점수를 의미하는 딕셔너리 {'Python': 95, 'SQL': 85, 'Web': 90}를 활용하여 또 다른 Series를 생성하세요.


import pandas as pd

lis = [85, 92, 78, 90, 88]

sr = pd.Series(lis)
print(sr)
print()

sr1 = pd.Series(lis,index = ['Alice', 'Bob', 'Charlie', 'David', 'Eve'] )
print(sr1)
print()

dic_data = {'Python': 95, 'SQL': 85, 'Web': 90}

sr2 = pd.Series(dic_data)

print(sr2)

0    85
1    92
2    78
3    90
4    88
dtype: int64

Alice      85
Bob        92
Charlie    78
David      90
Eve        88
dtype: int64

Python    95
SQL       85
Web       90
dtype: int64

In [37]:
# [문제 2] 올바른 인덱싱과 데이터 추출 

# [문제 1]에서 만든 학생 점수 Series를 활용하여 아래 작업을 수행하세요. 
# 인덱스 위치(Position)와 레이블(Label)을 헷갈리지 않도록 주의하세요.

# 'Charlie'의 점수를 단일 레이블 인덱싱을 통해 추출하세요.

# 두 번째부터 네 번째 학생('Bob', 'Charlie', 'David')의 점수를 위치 기반 슬라이싱을 통해 추출하세요.


label1 = sr1.loc["Charlie"]
print(label1)

position1 = sr1.iloc[1:4]
print(position1)

78
Bob        92
Charlie    78
David      90
dtype: int64