In [1]:
# CSV파일
## pandas.read_csv("파일 경로(이름)")

import pandas as pd
import os

os.listdir("./data")
# pd.read_csv()

['read_csv_sample.csv']

In [4]:
file_path = "./data/read_csv_sample.csv"
print(file_path)

./data/read_csv_sample.csv

In [5]:
file_path2 = os.path.join("data","read_csv_sample.csv")

print(file_path2)

data\read_csv_sample.csv

In [10]:
df1 = pd.read_csv(file_path)

df1

   c0   c1   c2   c3
0   0    1    4    7
1   1    2    5    8
2   2    3    6    9

In [8]:
df2 = pd.read_csv(file_path, header=None)
df2

    0    1    2    3
0  c0   c1   c2   c3
1   0    1    4    7
2   1    2    5    8
3   2    3    6    9

In [ ]:
df3 = pd.read_csv(file_path, index_col = None)
df3

   c0   c1   c2   c3
0   0    1    4    7
1   1    2    5    8
2   2    3    6    9

In [11]:
df4 = pd.read_csv(file_path, index_col = "c0")
df4

    c1  c2  c3
c0
0    1   4   7
1    2   5   8
2    3   6   9

In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\Win11Pro\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)

In [3]:
# excel 파일

# pandas.read_excel("파일경로")

import pandas as pd

df = pd.read_excel("./data/남북한발전전력량.xlsx", engine="openpyxl")
df.head()

,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
1,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
2,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
3,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620
4,NaN,신재생,-,-,-,-,-,-,-,-,...,-,-,-,-,-,86,118,151,173,195

In [7]:
df2 = pd.read_excel("./data/남북한발전전력량.xlsx", engine="openpyxl", header=None)
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,전력량 (억㎾h),발전 전력별,1990,1991,1992,1993,1994,1995,1996,1997,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
1,남한,합계,1077,1186,1310,1444,1650,1847,2055,2244,...,4031,4224,4336,4747,4969,5096,5171,5220,5281,5404
2,NaN,수력,64,51,49,60,41,55,52,54,...,50,56,56,65,78,77,84,78,58,66
3,NaN,화력,484,573,696,803,1022,1122,1264,1420,...,2551,2658,2802,3196,3343,3430,3581,3427,3402,3523
4,NaN,원자력,529,563,565,581,587,670,739,771,...,1429,1510,1478,1486,1547,1503,1388,1564,1648,1620

In [8]:
# json파일
## pandas.read_json("파일경로")
import pandas as pd

df = pd.read_json("./data/read_json_sample.json")

df

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

In [10]:
df2 = pd.read_json("./data/read_json_sample.json", orient="index")
df2

                   pandas            NumPy      matplotlib
year                 2008             2006            2003
developer   Wes Mckinneye  Travis Oliphant  John D. Hunter
opensource           True             True            True

In [11]:
df3 = pd.read_json("./data/read_json_sample.json", orient="columns")

df3

            year        developer opensource
pandas      2008    Wes Mckinneye       True
NumPy       2006  Travis Oliphant       True
matplotlib  2003   John D. Hunter       True

In [14]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 4.1/4.1 MB 31.0 MB/s  0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.1.1

In [18]:
# 웹에서 가져오기

# pandas.read_html("파일경로")

import pandas as pd

url = "./data/sample.html"
tables = pd.read_html(url)
print(len(tables))

for i in range(len(tables)):
    print(f"tables{i}")
    print(tables[i])
    print()

2
tables0
   Unnamed: 0  c0  c1  c2  c3
0           0   0   1   4   7
1           1   1   2   5   8
2           2   2   3   6   9

tables1
         name  year        developer  opensource
0       NumPy  2006  Travis Oliphant        True
1  matplotlib  2003   John D. Hunter        True
2      pandas  2008    Wes Mckinneye        True